import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { createClient } from 'contentful';
import ProjectCard from '../components/ProjectCard';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_DELIVERY_API,
  });

  const res = await client.getEntries({ content_type: 'project' });

  return {
    props: {
      // any objects added are passing as a props called 'projects'
      projects: res.items,
    },
  };
}

export default function Projects({ projects }) {
  return (
    <>
      <Head>
        <title>Projects in TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.cards}>
        {projects.map((project) => (
          <ProjectCard key={project.sys.id} project={project} />
        ))}
      </div>
    </>
  );
}
